### ISSUE TITLE
store initialization

### ISSUE THREAD

**Issue by pablodeafsapps** [ReKotlin/ReKotlin#11]
Hi! I have been playing with this library for a while; let me tell you first of all that it looks great. I have always liked the Redux concept put in practice in web development, so thank you for bringing it out for Android :).

My question has to do with the store initialization. Basically, I do not understand why  you do,
```kotlin
val mainStore = Store(
    reducer = ::counterReducer, 
    state = null
)
```

instead of,
```kotlin
val mainStore = Store(
    reducer = ::counterReducer, 
    state = AppState()
)
```

I mean, according to the Redux concept, the app should always be in a particular state. I know the whole library is null-safety (?), but I have changed things as proposed and everything seems to work fine! Could you please shed some light on this  matter? 
Regards,

**Comment by ambientlight** [comment]
This would certainly work.
`null` is set there, so that the counter reducer can handle initial case(`null`) in the way he wants. This is essentially one way how you can distinguish an initial state change in a reducer, it has been used as more or less a convention in original `redux` and `ReSwift`.

fun counterReducer(action: Action, state: AppState?): AppState {
    // if no state has been provided, create the default state
    var state = state ?: AppState()
    // other logic
}
```

**Comment by ambientlight** [comment]
I understand that you are making the state parameter non-nullable here because it makes your reducer function cleaner.

ReKotlin implementation is actually a port of ReSwift and thus in type definitions I tried to adhere to theirs as close as possible, that is why there is precisely:

```kotlin
typealias Reducer<ReducerStateType> = (action: Action, state: ReducerStateType?) -> ReducerStateType
```

My best suggestion to you would be to just stick with original reducer definition. I personally think that handling null state in reducer is a good practice (also somehow a conventional way).

**Comment by pablodeafsapps** [comment]
Thanks! I just wanted to get your thoughts about this. I know this is based on ReSwift, and thus it tries to replicate every aspect of that magnificent piece of code. I will stick to the library, of course, but I think I will end up initializing the states anyway, so I ensure to myself that the application will always have a particular non-null state. 
Regars!
